# Site settings
title: YB
email: sea5sky2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://sea5sky2.github.io/" # the base hostname & protocol for your site
github_username: sea5sky2

# Build settings
markdown: kramdown
